stages:
  - build-deploy

build-deploy:
  stage: build-deploy
  before_script:
    - echo "@adameds:registry=https://gitlab.com/api/v4/groups/93029767/-/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/groups/93029767/-/packages/npm/:_authToken=$AUTH_TOKEN" >> .npmrc
    - docker compose --env-file /home/engineer/adameds/.env.lab down --rmi all
  only:
    - dev-deployment
  script:
    - docker compose --env-file /home/engineer/adameds/.env.lab up -d
